CREATE TABLE [dbo].[UsersInfo](
	[Username] [varchar](20) NOT NULL,
	[HashedPwd] [varchar](200) NULL,
	[Salt] [varchar](100) NULL,
 CONSTRAINT [PK_UsersInfo] PRIMARY KEY CLUSTERED 
(
	[Username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO